[Win] Temporarily run browser tests with --disable-gpu-sandbox.
Browser tests error out on Windows CI with

content/public/test/test_utils.cc(137): error: Failed
RunLoop::Run() timed out. Timeout set at ProxyRunTestOnMainThreadLoop@content/public/test/browser_test_base.cc:800.

Running with --disable-gpu avoids the error, but causes various WebGL
tests to fail.

Running with --no-sandbox avoids the error.

Running with --disable-gpu-sandbox also avoids the error - picked this
one is the least bad from the 2 above.

It is not clear ATM what's causing the error.

Only adds the flag on Windows in Release config.